prometheus:
  prometheusSpec:
    replicas: 1
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

server:
  extraArgs:
    - "--tracer.address=jaeger-agent.monitoring.svc.cluster.local:6831"

alertmanager:
  alertmanagerSpec:
    replicas: 1
    externalUrl: "http://alertmanager.monitoring.svc.cluster.local"

grafana:
  enabled: true
  adminPassword: "admin"

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "true"
    datasources:
      enabled: true

  tracing:
    enabled: true
    jaeger:
      agentHost: "jaeger-agent.monitoring.svc.cluster.local"
      agentPort: 6831
