apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-secret-reader
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-postgres-secret
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace | quote}}
roleRef:
  kind: Role
  name: postgres-secret-reader
  apiGroup: rbac.authorization.k8s.io
