apiVersion: v1
kind: Service
metadata:
  name: url-app
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: url-app
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
