apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: {{ .Release.Namespace | quote }}
data:
  # Would like to avoid hard coding sql query. Need to somehow grab from migtations/init.sql
  create_tables.sql: |
    CREATE TABLE url (
      mapping_id SERIAL PRIMARY KEY,
      created_at TIMESTAMP NOT NULL,
      old_url    VARCHAR(255) NOT NULL UNIQUE,
      shortkey   VARCHAR(255) NOT NULL UNIQUE
    );
