apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
