name: 'Docker Build and Attest'
description: 'Build Docker image with Buildx and generate attestation'
inputs:
  registry:
    description: 'Docker registry domain (e.g., ghcr.io)'
    required: true
  image_name:
    description: 'Image name (e.g., user/repo)'
    required: true
  tags:
    description: 'Docker tags (comma-separated)'
    required: true
  context:
    description: 'Build context path'
    required: false
    default: '.'
  push_on_build:
    description: 'Whether to push the image'
    required: false
    default: 'true'
  labels:
    description: 'Optional Docker image labels'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push_on_build }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
