config: |
  server:
    http_listen_port: 3200
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

persistence:
  enabled: true
  storageClassName: "standard"
  size: 1Gi
  accessModes:
    - ReadWriteOnce

service:
  type: ClusterIP
  port: 3100

securityContext:
  fsGroup: 1000
  runAsUser: 1000

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

distributor:
  config:
    log_received_spans:
      enabled: true
    log_discarded_spans:
      enabled: true
