name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: write
  attestations: write
  id-token: write

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.7
        with:
          args: --redact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  go-lint:
    runs-on: ubuntu-latest
    needs: check-secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.1.5/golangci-lint-2.1.5-linux-amd64.tar.gz | tar -xzv
          mv golangci-lint-*/golangci-lint /usr/local/bin/

      - name: Run Go Lint
        run: golangci-lint run

  go-tests:
    runs-on: ubuntu-latest
    needs: go-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'
      
      - name: Run Go Tests with Coverage
        run: |
          go mod tidy
          go test ./... -coverprofile=coverage.out -v

      - name: Display Coverage as Table
        run: |
          echo "Displaying coverage summary as a table:"
          go tool cover -func=coverage.out

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: go-tests
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: ./.github/actions/docker-build
        with:
          registry: ghcr.io
          image_name: ${{ github.repository }}
          push_on_build: true
          context: .
          tags: 'latest,${{ github.sha }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
